version: '3.9'
services:
  db:
    container_name: 'mysql-db'
    image: 'mysql:latest'
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './data/schema:/docker-entrypoint-initdb.d'
    env_file:
      - .env

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress

  wordpress:
    container_name: 'wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
