version: '3.9'
services:
  db:
    container_name: 'mysql-db'
    platform: linux/x86_64
    image: 'mysql:latest'
    volumes:
      - './data/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress 

  wordpress:
    container_name: 'wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      # - "./wptest/wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
